name: Pipeline CI/CD - Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
# Etapa de CI (Integração contínua)
  validacao-html:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código
      uses: actions/checkout@v4
    
    - name: Configurar Node.js (Ambiente de Linter)
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar validador de html
      run: npm install -g htmlhint

    - name: Validar Arquivos html
      # run: htmlhint "index.html"
      run: htmlhint "**/*.html"

  # Etapa de CD (Entrega contínua)
  deploy-producao:
    needs: validacao-html
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar o Github Pages
      uses: actions/configure-pages@v4

    - name: Compactar Artefatos do Site
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Publica no Github Pages
      uses: actions/deploy-pages@v4